test test test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,7 +77,12 @@ jobs:
       - name: Check if code is up to date
         run: |
           git --no-pager diff
-          ./scripts/diff.sh
+          if [[ $(git status --porcelain=v1 2>/dev/null) ]]; then
+            echo "❌ Error: gRPC service is not up to date. Please run 'make gen' and commit your changes."
+            exit 1
+          else
+            echo "✅ gRPC service is up to date."
+          fi
 
   build:
     name: build
