doc/ci: update `README` and add ci job to check the code is up to date (#10)
* doc: update `README`

* test: update test script to make sure curl and grpcurl are installed before running tests

* ci: make sure gRPC service code is up to date

* fix: use sudo to download protobuf package and also use `apt` instead of `apt-get`

* ci: fix install `protoc-gen-go`

* ci: fix the install cmd

* ci: fix protoc install issue

* chore: generate code

* ci: fix typo

* ci: run `up-to-date` job before `build` and `test`

* test: make a change to proto file without generating code

* ci: fix up-to-date job

* fix: revert change

* chore: gen code

* ci: fix test job

* ci: raise error

* ci: add debug

* ci: clean up

* ci: display protoc versions

* ci: run apt update

* ci: more debug

* ci: install a specific version of protoc

* ci: fix typo

* ci: install zip instead of tar

* ci: another test

* ci: update test job

* ci: also extract proto definitions

* ci: remove wrong cmd

* ci: fix issue

* ci: change git status check

* test: code not updated

* fix: typo

* Revert "test: code not updated"

This reverts commit 19caec2aae09c5829b6f74d1f74f16a532942cf1.

* test

* test2

* test

* test

* test

* test: another one ...

* another test

* test

* test test test

* test

* test 💣

* test: remove cmd check

* test

* teet

* final test?

* test: revert change to proto

* ci: clean up

* test: simplify test script

* ci: last fix please

* ci: add back feature to check for services

* ci: remove build job

* fix typo

* simple test

* last clean up!!! 🎉

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,6 +17,10 @@ concurrency:
 
 env:
   GO_VERSION: "1.21"
+  # Check https://grpc.io/docs/languages/go/quickstart/ for `protoc` versions.
+  PROTOC_VERSION: "23.4"
+  PROTOC_GEN_GO_VERSION: "1.28"
+  PROTOC_GEN_GO_GRPC_VERSION: "1.2"
 
 jobs:
   lint:
@@ -40,9 +44,49 @@ jobs:
       - name: Run linters
         run: make lint
   
-  build:
-    name: build
-    needs: lint
+  up-to-date:
+    name: up-to-date
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v3
+      
+      - name: Install protoc
+        run: |
+          wget https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip
+          unzip protoc-23.4-linux-x86_64.zip
+          sudo mv bin/protoc /usr/local/bin/
+          sudo mv include/google /usr/local/include
+          protoc --version
+      
+      - name: Install go
+        uses: actions/setup-go@v4
+        with:
+          go-version: ${{ env.GO_VERSION }}
+
+      - name: Install protoc plugins for go
+        run: |
+          go install google.golang.org/protobuf/cmd/protoc-gen-go@v${{ env.PROTOC_GEN_GO_VERSION }}
+          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v${{ env.PROTOC_GEN_GO_GRPC_VERSION }}
+          protoc-gen-go --version
+          protoc-gen-go-grpc --version
+
+      - name: Generate code
+        run: make gen
+
+      - name: Check if code is up to date
+        run: |
+          git update-index --really-refresh
+          if $(git diff-index --quiet HEAD); then 
+            echo "✅ gRPC service is up to date."
+          else
+            echo "❌ Error: gRPC service is not up to date. Please run 'make gen' and commit your changes."
+            exit 1
+          fi
+
+  test:
+    name: test
+    needs: [lint, up-to-date]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout sources
@@ -54,15 +98,7 @@ jobs:
           go-version: ${{ env.GO_VERSION }}
 
       - name: Build code
-        run: go build main.go
-  
-  test:
-    name: test
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@v3
+        run: go build -o mock-server main.go
       
       - name: Install grpcurl
         run: |
@@ -71,14 +107,8 @@ jobs:
           sudo mv grpcurl /usr/local/bin/
           sudo chmod +x /usr/local/bin/grpcurl
           grpcurl --version
-      
-      - name: Install go
-        uses: actions/setup-go@v4
-        with:
-          go-version: ${{ env.GO_VERSION }}
-      
-      - name: Run the mock server in background
-        run: go run main.go --http-port 8080 --http-save-endpoint /save --grpc-port 8546 --output-dir out &
 
       - name: Run tests
-        run: make test
+        run: |
+          ./mock-server --http-port 8080 --http-save-endpoint /save --grpc-port 8546 --output-dir out &
+          make test
